#!/bin/bash
sudo hdfs dfs -rm -r /user/cloudera/customerspeed/

sqoop job --exec batchlayer

var=$(mysql --user=root --password=cloudera retail_db -s -e "select max(customer_id) from customers;")

sqoop job --delete speedlayer

sqoop job -D sqoop.metastore.client.record.password=true --create speedlayer -- import --connect jdbc:mysql://localhost/retail_db --table customers --username root --password cloudera --check-column customer_id --incremental append --last-value $var -m 1 --target-dir /user/cloudera/customerspeed/